version: '3,8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: '3.1.2'
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/user/local/bundle
    depends_on:
      - redis
      - postgres
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000

  #  sidekiq:
  #    <<: *base
  #    command: bundle exec sidekiq -C config/sidekiq.yml

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/.env
    environment:
      - POSTGRES_USER=interface_mobile_dev
      - POSTGRES_PASSWORD=interface_mobile_dev
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

volumes:
  bundle:
  postgres_data: