ARG RUBY_VERSION
FROM ruby:$RUBY_VERSION

RUN apt-get update -qq && \
    apt-get install -y build-essential \
    libvips \
    bash \
    bash-completion \
    libffi-dev \
    tzdata \
    postgresql && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

COPY \
  Gemfile \
  Gemfile.lock \
  ./

WORKDIR ./backend

RUN gem update --system
RUN bundle install -j $(nproc)
